### ISSUE TITLE
Default sigma value

### ISSUE THREAD

**Issue by yueqiw** [chriscainx/mnnpy#11]
Hi,

The `mnnCorrect()` function in Scran has a default sigma=0.1, and your package has sigma=1.0 by default. Are these sigma values on different scales or is there a reason for using different sigma values? Thanks!

**Comment by chriscainx** [comment]
It's a recent change made by Aaron Lun in Scran. He didn't seem to post the reasons for this change. I the old version of Scran it's 1.0 by default. I'll update it according to scran.
