### ISSUE TITLE
 OverflowError: cannot serialize a bytes object larger than 4 GiB

### ISSUE THREAD

**Issue by yxaxaxa** [chriscainx/mnnpy#17]
sorry for this, but when I try to use mnn to practice batch effect correction, and one sample is 68K pbmc, the other is 3k PBMC. When I tried to use mnn, the python shows:
OverflowError: cannot serialize a bytes object larger than 4 GiB
the whole procedure was list below:

```
path = './PBMC_3K/'
adata1 = sc.read(path + 'matrix.mtx', cache=True).T  # transpose the data
adata1.var_names = pd.read_csv(path + 'genes.tsv', header=None, sep='\t')[1]
adata1.obs_names = pd.read_csv(path + 'barcodes.tsv', header=None)[0]

```
```
path = './PBMC_68k/'
adata = sc.read(path + 'matrix.mtx', cache=True).T  # transpose the data
adata.var_names = pd.read_csv(path + 'genes.tsv', header=None, sep='\t')[1]
adata.obs_names = pd.read_csv(path + 'barcodes.tsv', header=None)[0]
```
```
corrected = mnnpy.mnn_correct(adata1, adata, batch_categories = ["3K", "68k"])
adata = corrected[0]
```
Would you please help me how to fix this problem?

**Comment by chriscainx** [comment]
Looks like a problem of python's pickle... I will take a look when i have time

**Comment by connerlambden** [comment]
Any updates on this? Same issue with Python 3.7. Thanks!

**Comment by ygidtu** [comment]
> Any updates on this? Same issue with Python 3.7. Thanks!

There is a temporary walk around. 

1. Replace the `parallel` in the`mnnpy/settings.py` with any string you like. 
2. Re-install mnnpy
This will force to disable the multiprocessing. Therefore, your code should work, besides it will super slow.

Personally, I met this error before in my own project. So I might have a solution for this, and I'm working on it

**Comment by chriscainx** [comment]
I'm rewriting the package in c and openmp, hopefully we won't have to deal with such problems. Quick question: have you tried fastmnn (from the original authors, using PCs instead of genes for batch alignment)? What do you think if we use PCs in newer versions?

**Comment by ygidtu** [comment]
> fastmnn

Thanks for you reply, I haven't try fastmnn yet, I will check it out. 

This issue as far as I know, python seems have a limit of the size of the data that exchanges between processes. It like `-2147483648 <= data size <= 2147483647`. Actually, this is what I met before, may data is oversize in some extreme cases.

I'm not familiar with C and openmp, so can't tell if this would happen again.

As PCs and genes as a researcher, I would like to have a option to switch between genes and PCs to see which one is better for specific case.

**Comment by ygidtu** [comment]
All right I give up. Python has a limitation on data size that passed between processes, the `scale_rows` will try to return a whole array, which is easy to oversize. The only way in python is split different rows into different processes and using `Queue` or [`shared memory`](https://stackoverflow.com/questions/5549190/is-shared-readonly-data-copied-to-different-processes-for-multiprocessing/5550156#5550156) to collect the results.  
But using `Queue` seems never as fast as `numpy` and cause a huge memory usage. 

So I believe the `shared_memory` maybe better for this problem, I still gonna try it, if I have any time
