### ISSUE TITLE
fortmat for HVG file

### ISSUE THREAD

**Issue by ypzz** [chriscainx/mnnpy#5]
Hi, 

Thank you for the work! I am trying out the package and it works well for me without specifying HVGs. But when I specify HVGs, it return error like "ValueError: Some items in var_subset are not in var_index.".  So I was wondering what is the format of HVG file, i.e. what are in columns and rows?

**Comment by chriscainx** [comment]
It's a list of names like ['G1', 'G2', 'G4'], or a list of index like [0, 2, 4]
